### ISSUE TITLE
Apply Object Detection 

### ISSUE THREAD

**Issue by Dhruv-194** [LetsUpgrade/FOOTSTEP-APP#14]
**Implement:** Object Detection activity using tensorflow

**Type:** UI XML & Java

**Context:** In the 'ObjectDetection' activity created during the past issue implementation you need to apply Object Detection using pre trained models of tensorflow/tensorflow lite which returns a text on recognizing the object .

**Comment by Bijay555** [comment]
@Dhruv-194  Can you assign this to me?
