### ISSUE TITLE
Create a computer generated audio which gives certain instructions

### ISSUE THREAD

**Issue by Dhruv-194** [LetsUpgrade/FOOTSTEP-APP#3]
**What is to be done -** 
On the first activity/screen ( after the splash screen ) add text and an audio file which gives instruction to the user of how to use the app. The audio can be your own recorded or a computer one which speaks in english and tell user what to do.

**Comment by Bijay555** [comment]
@Dhruv-194 I have a question. Like do I have to wait until issue#2 is fixed before doing this . Or I can start doing it?

**Comment by Dhruv-194** [comment]
@Bijay555 you can start working on this. But we have to remember that we add the splash screen activity  #2  before this.
